name: Depolyment

on:
    push:
        branches: [master]

jobs:
    depoly:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup Node
              uses: actions/setup-node@v2
              with:
                  node-version: "12"

            - name: Install Dependencies
              run: npm install
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Check
              run: npm run check

            - name: Build
              run: npm run build

            - name: copy package.json
              uses: canastro/copy-file-action@master
              with:
                  source: "package.json"
                  target: "dist/package.json"

            - name: copy README.md
              uses: canastro/copy-file-action@master
              with:
                  source: "README.md"
                  target: "dist/README.md"

            - name: Deploy
              run: npm publish
              working-directory: ./dist
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
